### ISSUE TITLE
Checklist for the Unittest:

### ISSUE THREAD

**Issue by Marius9610** [bchwtz/bchwtz-gateway#49]
- [x] create a `gateway_unittest.yml` GitHub Workflow
- [x] Test1: Install dependencies with the setup.txt
- [x] Test2: Running setup.py
- [x] Test3: Test the gateway.hub submodule with pytest
- [x] Test4: Test the gateway.sensor submodule with pytest
